name = "HomotopyLasso"
uuid = "dbdef399-7c69-4bd0-8734-f2accf45dfff"
authors = ["Johan Larsson <johanlarsson@outlook.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
